# Generated by Django 6.0.4 on 2026-04-24 00:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, default='SD', max_length=20)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('creatine_mg', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.day')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_composite', models.BooleanField(default=False)),
                ('calories', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('fat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sat_fat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('cholesterol', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('add_sugar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('protein', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.day')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.food')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='NapLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_time', models.TimeField()),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nap', to='api.day')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('total_grams_produced', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.food')),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('bedtime', models.TimeField()),
                ('wake', models.TimeField()),
                ('meds', models.BooleanField(default=False)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to='api.day')),
            ],
        ),
        migrations.CreateModel(
            name='UserTargets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fat_pct_low', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5)),
                ('fat_pct_high', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=5)),
                ('sat_fat_pct_low', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('sat_fat_pct_high', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('carb_pct_low', models.DecimalField(decimal_places=2, default=Decimal('45'), max_digits=5)),
                ('carb_pct_high', models.DecimalField(decimal_places=2, default=Decimal('65'), max_digits=5)),
                ('protein_pct_low', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('protein_pct_high', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=5)),
                ('added_sugar_pct_low', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('added_sugar_pct_high', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('cholesterol_low', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('cholesterol_high', models.DecimalField(decimal_places=1, default=Decimal('200'), max_digits=6)),
                ('sodium_low', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=7)),
                ('sodium_high', models.DecimalField(decimal_places=1, default=Decimal('2300'), max_digits=7)),
                ('fiber_low', models.DecimalField(decimal_places=1, default=Decimal('28'), max_digits=5)),
                ('fiber_high', models.DecimalField(decimal_places=1, default=Decimal('34'), max_digits=5)),
                ('protein_min', models.DecimalField(decimal_places=1, default=Decimal('90'), max_digits=5)),
                ('creatine_min', models.DecimalField(decimal_places=1, default=Decimal('5'), max_digits=5)),
                ('sleep_hours_low', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4)),
                ('sleep_hours_high', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=4)),
                ('sleep_quality_low', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_quality_high', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('goal_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.recipe')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('recipe', 'position')},
            },
        ),
    ]
