# Generated by Django 6.0.4 on 2026-04-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_day_exerciselog_food_meal_naplog_recipe_sleeplog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
