# Generated by Django 6.0.4 on 2026-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
